accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "BSL-1.0",
    "MPL-2.0",
    "GPL-3.0",
    "LGPL-3.0",
    "CC0-1.0",
    "Unicode-DFS-2016"
]
targets = [
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-gnu",
    "i686-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "universal-apple-darwin",
    "aarch64-pc-windows-msvc",
    "i686-pc-windows-msvc"
]
ignore-dev-dependencies = true