[package]
name = "ubilerntui"
version = "0.1.6"
edition = "2021"
authors = ["Adam McKellar"]
description = "This is a terminal UI for learning for the UKW-Sprechfunkzeugnis für den Binnenschiffahrtsfunk."
license = "GPL-3.0-or-later"
readme = "./README.md"
repository = "https://github.com/WyvernIXTL/ubilerntui"
keywords = ["lernen", "ubi", "ukw", "binnenschiffahrt", "sprechfunkzeugnis"]
categories = ["command-line-utilities"]


[dependencies]
tracing = {version = "0.1", features = ["release_max_level_info"]}
tracing-subscriber = {version = "0.3", features = ["json", "env-filter"]}
color-eyre = "0.6.2"
directories = "5.0.1"
tracing-error = "0.2.0"
chrono = "0.4.38"
crossterm = "0.27.0"
ratatui = "0.26.3"
rusqlite = {version = "0.31.0", features = ["bundled"]}
rand = "0.8.5"
clap = "4.5.4"
pdf-extract = "0.7.7"
regex = "1.10.4"
once_cell = "1.19.0"
colored = "2.1.0"
textwrap = {version = "0.16.1", features = ["hyphenation"]}
hyphenation = "0.8.4"

[dev-dependencies]
pretty_assertions = "1.4.0"

[package.metadata.deb]
maintainer = "Adam McKellar <dev@mckellar.eu>"
copyright = "2024, Adam McKellar"
changelog = "CHANGELOG.md"
section = "education"
priority = "optional"
license-file = "./LICENSE.txt"

