name: ubilerntui
version: git
summary: Eine Terminal UI, um für die "UKW-Sprechfunkzeugnis für den Binnenschiffahrtsfunk"-Prüfung zu lernen.
description: |
  Ein großer Unterschied zu anderen Programmen, die das Gleiche versprechen, ist hier, dass die Fragen direkt eingelesen werden aus der PDF.
  Sie können entsprechend den neuesten, offiziellen Fragenkatalog online finden und mit diesem Programm automatisch parsen.

base: core22
confinement: devmode

parts:
  ubilerntui:
    plugin: rust
    source: .

apps:
  ubilerntui:
    command: bin/ubilerntui

