name: ubilerntui
version: git
summary: UKW-Sprechfunkzeugnis für den Binnenschiffahrtsfunk-Prüfung Lern-Terminal-UI
description: |
  Ein großer Unterschied zu anderen Programmen, die das Gleiche versprechen, ist hier, dass die Fragen direkt eingelesen werden aus der PDF.
  Sie können entsprechend den neuesten, offiziellen Fragenkatalog online finden und mit diesem Programm automatisch parsen.

website: https://github.com/WyvernIXTL/ubilerntui
issues: https://github.com/WyvernIXTL/ubilerntui/issues
grade: stable
license: GPL-3.0-or-later

base: core22
confinement: strict

parts:
  ubilerntui:
    plugin: rust
    source: .

apps:
  ubilerntui:
    command: bin/ubilerntui
    plugs:
      - home

