name: Release

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  compile-and-upload:
    continue-on-error: true
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: i686-pc-windows-msvc
            os: windows-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Target
        run: rustup target add ${{ matrix.target }}
      - name: Compile
        run: cargo build --release --target ${{ matrix.target }}
      - name: Zip Binary (windows)
        if: runner.os == 'Windows'
        run: 7z a ubilerntui-${{ matrix.target }}.7z ./target/${{ matrix.target }}/release/ubilerntui.exe ./CHANGELOG.md ./README.md
      - name: Tar Binary (linux/mac)
        if: runner.os != 'Windows'
        run: tar -cJf ubilerntui-${{ matrix.target }}.tar.xz ./target/${{ matrix.target }}/release/ubilerntui ./CHANGELOG.md ./README.md
      - name: Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ubilerntui*

  compile-and-upload-cross:
    continue-on-error: true
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: i686-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Compile
        run: cross build --release --target ${{ matrix.target }}
      - name: Zip Binary (windows)
        if: runner.os == 'Windows'
        run: 7z a ubilerntui-${{ matrix.target }}.7z ./target/${{ matrix.target }}/release/ubilerntui.exe ./CHANGELOG.md ./README.md
      - name: Tar Binary (linux/mac)
        if: runner.os != 'Windows'
        run: tar -cJf ubilerntui-${{ matrix.target }}.tar.xz ./target/${{ matrix.target }}/release/ubilerntui ./CHANGELOG.md ./README.md
      - name: Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ubilerntui*

  package-and-release-snap:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, riscv64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - uses: snapcore/action-build@v1
        id: snapbuild
        with:
          snapcraft-args: --build-for ${{ matrix.arch }}
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.snapbuild.outputs.snap }}
          release: stable

  package-and-release-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Cargo Deb
        shell: bash
        run: "cargo install cargo-deb"
      - name: Compile
        shell: bash
        run: "cargo deb -o ./target/debian/ubilerntui-x64.deb"
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/debian/ubilerntui-x64.deb
      