name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2

  compile-and-upload:
    permissions:
      contents: write
    continue-on-error: true
    needs: [create-release]
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: i686-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: i686-pc-windows-msvc
            os: windows-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Target
        run: rustup target add ${{ matrix.target }}
      - name: Compile
        run: cargo build --release --target ${{ matrix.target }}
      - name: Zip Binary (windows)
        if: runner.os == 'Windows'
        run: Compress-Archive -Path ./target/${{ matrix.target }}/release/${{ env.NAME }}.exe -DestinationPath ${{ env.NAME }}-${{ matrix.target }}.zip
      - name: Tar Binary (linux/mac)
        if: runner.os != 'Windows'
        run: tar -cJf ${{ env.NAME }}-${{ matrix.target }}.tar.xz ./target/${{ matrix.target }}/release/${{ env.NAME }}
      - name: Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.NAME }}*

  package-and-release-snap:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, riscv64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - uses: snapcore/action-build@v1
        id: snapbuild
        with:
          snapcraft-args: --build-for ${{ matrix.arch }}
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.snapbuild.outputs.snap }}
          release: stable

  package-and-release-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Cargo Deb
        shell: bash
        run: "cargo install cargo-deb"
      - name: Compile
        shell: bash
        run: "cargo deb -o ./target/debian/ubilerntui-x64.deb"
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/debian/ubilerntui-x64.deb
      