name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  cargo-3pl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Cargo 3pl
        shell: bash
        run: "cargo install cargo-3pl"
      - name: Remove old 3rd Party Licenses
        shell: bash
        run: "rm -f ./LICENSE-3RD-PARTY.txt"
      - name: Generate 3rd Party Licenses
        shell: bash
        run: "cargo 3pl > ./LICENSE-3RD-PARTY.txt"
      - name: Add dict license to 3r party licenses
        shell: bash
        run: "cat ./dictionary/LICENSE-DICTIONARY.txt >> ./LICENSE-3RD-PARTY.txt"
      - name: Upload as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 3rd-party-licenses-artifact
          path: ./LICENSE-3RD-PARTY.txt
          if-no-files-found: error
          retention-days: 1

  compile-and-upload:
    needs: [create-release, cargo-3pl]
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: i686-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: universal-apple-darwin
            os: macos-latest
          - target: i686-pc-windows-msvc
            os: windows-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Remove old 3rd Party Licenses
        shell: bash
        run: "rm -f ./LICENSE-3RD-PARTY.txt"
      - name: Download 3rd Party Licenses
        uses: actions/download-artifact@v4
        with:
          name: 3rd-party-licenses-artifact
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ubilerntui
          target: ${{ matrix.target }}
          archive: $bin-$tag-$target
          checksum: sha256
          include: LICENSE.txt,README.md,LICENSE-3RD-PARTY.txt,CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  package-and-release-snap:
    needs: [cargo-3pl]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, riscv64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Remove old 3rd Party Licenses
        shell: bash
        run: "rm -f ./LICENSE-3RD-PARTY.txt"
      - name: Download 3rd Party Licenses
        uses: actions/download-artifact@v4
        with:
          name: 3rd-party-licenses-artifact
      - uses: snapcore/action-build@v1
        id: snapbuild
        with:
          snapcraft-args: --build-for ${{ matrix.arch }}
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.snapbuild.outputs.snap }}
          release: stable

  package-and-release-deb:
    needs: [cargo-3pl]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Cargo Deb
        shell: bash
        run: "cargo install cargo-deb"
      - name: Remove old 3rd Party Licenses
        shell: bash
        run: "rm -f ./LICENSE-3RD-PARTY.txt"
      - name: Download 3rd Party Licenses
        uses: actions/download-artifact@v4
        with:
          name: 3rd-party-licenses-artifact
      - name: Compile
        shell: bash
        run: "cargo deb -o ./target/debian/ubilerntui-x64.deb"
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/debian/ubilerntui-x64.deb
      