name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  cargo-about:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Cargo About
        shell: bash
        run: "cargo install --locked cargo-about"
      - name: Generate 3rd Party Licenses
        shell: bash
        run: "cargo about generate about.hbs > LICENSE-3RD-PARTY.html"
      - name: Upload as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 3rd-party-licenses-artifact
          path: ./LICENSE-3RD-PARTY.html
          if-no-files-found: error
          retention-days: 1

  compile-and-upload:
    needs: [create-release, cargo-about]
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: i686-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: universal-apple-darwin
            os: macos-latest
          - target: i686-pc-windows-msvc
            os: windows-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Download 3rd Party Licenses
        uses: actions/download-artifact@v4
        with:
          name: 3rd-party-licenses-artifact
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ubilerntui
          target: ${{ matrix.target }}
          archive: $bin-$tag-$target
          checksum: sha256
          include: LICENSE.txt,README.md,LICENSE-3RD-PARTY.html,./dictionary/LICENSE-DICTIONARY.txt
          token: ${{ secrets.GITHUB_TOKEN }}